#!/usr/bin/env python3
"""Build giacoballoccu/MetalSlugClone (Unity 2018.3 WebGL) → public/games/slug/

Steps performed:
  1. Clone the repo (or use --project for an existing clone).
  2. Auto-detect Unity 2018.3.x in Unity Hub; or pass --unity explicitly.
  3. Inject Assets/Editor/WebGLBuilder.cs into the project.
  4. Run Unity in -batchmode to produce a WebGL build.
  5. Copy build output to public/games/slug/.
  6. Patch Unity's generated index.html to inject the NEOARCADE gamepad bridge
     (makes mobile controllers work via postMessage → navigator.getGamepads()).

Usage:
  python scripts/build-slug.py
  python scripts/build-slug.py --unity "C:/path/to/Unity.exe"
  python scripts/build-slug.py --project "C:/path/to/clone" --keep
"""

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_URL = "https://github.com/giacoballoccu/MetalSlugClone.git"
UNITY_VERSION = "2018.3.8f1"

# Where the WebGL output lands inside public/
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "public" / "games" / "slug"

# Common Unity Hub installation locations (Windows)
UNITY_HUB_ROOTS: list[Path] = [
    Path(r"C:\Program Files\Unity\Hub\Editor"),
    Path(r"C:\Program Files (x86)\Unity\Hub\Editor"),
    Path(r"C:\Program Files\Unity\Editor"),
    Path(r"C:\Program Files (x86)\Unity\Editor"),
]

# ---------------------------------------------------------------------------
# C# build script injected into the Unity project at build time
# ---------------------------------------------------------------------------
WEBGL_BUILDER_CS = r"""// AUTO-GENERATED by NEOARCADE build-slug.py — safe to delete after build
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;

public static class WebGLBuilder
{
    private const string OutputPath = "WebGLBuild";

    public static void Build()
    {
        // Collect .unity files from EditorBuildSettings; fall back to all files
        // under Assets/Scenes if none are configured.
        string[] scenes = EditorBuildSettings.scenes
            .Where(s => s.enabled)
            .Select(s => s.path)
            .ToArray();

        if (scenes.Length == 0)
        {
            Debug.LogWarning("No scenes in BuildSettings — scanning Assets/Scenes/*.unity");
            scenes = Directory
                .GetFiles("Assets/Scenes", "*.unity", SearchOption.AllDirectories)
                .Select(p => p.Replace('\\', '/'))
                .OrderBy(p => p)
                .ToArray();
        }

        Debug.Log($"Building {scenes.Length} scene(s): {string.Join(", ", scenes)}");

        // Force WebGL compression to None (avoids needing a server with
        // correct MIME types for .gz / .br files).
        PlayerSettings.WebGL.compressionFormat = WebGLCompressionFormat.Disabled;

        var opts = new BuildPlayerOptions
        {
            scenes             = scenes,
            locationPathName   = OutputPath,
            target             = BuildTarget.WebGL,
            options            = BuildOptions.None,
        };

        BuildReport report = BuildPipeline.BuildPlayer(opts);

        if (report.summary.result == BuildResult.Succeeded)
        {
            Debug.Log($"[NEOARCADE] WebGL build succeeded — {report.summary.totalSize} bytes");
            EditorApplication.Exit(0);
        }
        else
        {
            Debug.LogError($"[NEOARCADE] WebGL build FAILED: {report.summary.result}");
            EditorApplication.Exit(1);
        }
    }
}
"""

# ---------------------------------------------------------------------------
# JS gamepad bridge injected into Unity's index.html
# Maps NEOARCADE postMessage events → navigator.getGamepads() virtual pads
# ---------------------------------------------------------------------------
GAMEPAD_BRIDGE_JS = r"""
<script>
/* NEOARCADE gamepad bridge — injected by build-slug.py */
(function () {
  'use strict';

  // Standard gamepad mapping button indices
  var BTN = { a: 0, b: 1, y: 3, start: 9 };
  // Axis indices and direction for d-pad
  var AXIS = { left: [0, -1], right: [0, 1], up: [1, -1], down: [1, 1] };

  function makeBtn(pressed) {
    return { pressed: !!pressed, touched: !!pressed, value: pressed ? 1.0 : 0.0 };
  }

  function makeGamepad(index) {
    return {
      id: 'NEOARCADE-P' + (index + 1) + ' (Virtual)',
      index: index,
      connected: false,
      timestamp: 0,
      mapping: 'standard',
      axes: new Float64Array(4),
      buttons: Array.from({ length: 17 }, function () { return makeBtn(false); }),
    };
  }

  var pads = [makeGamepad(0), makeGamepad(1)];
  var dispatched = [false, false];

  window.addEventListener('message', function (evt) {
    var d = evt.data;
    if (!d || d.type !== 'input') return;
    var idx = (d.player || 1) - 1;
    if (idx < 0 || idx > 1) return;

    var pad = pads[idx];
    var pressed = d.state === 'pressed';
    pad.timestamp = performance.now();

    if (BTN[d.button] !== undefined) {
      pad.buttons[BTN[d.button]] = makeBtn(pressed);
    } else if (AXIS[d.button]) {
      var axisIdx = AXIS[d.button][0];
      var dir     = AXIS[d.button][1];
      pad.axes[axisIdx] = pressed ? dir : 0;
    }

    if (!pad.connected) {
      pad.connected = true;
      if (!dispatched[idx]) {
        dispatched[idx] = true;
        window.dispatchEvent(new GamepadEvent('gamepadconnected', { gamepad: pad }));
      }
    }
  });

  // Patch navigator.getGamepads — Unity WebGL polls this every frame
  var _orig = navigator.getGamepads ? navigator.getGamepads.bind(navigator) : function () { return []; };
  navigator.getGamepads = function () { return pads; };

  console.log('[NEOARCADE] Gamepad bridge installed. Waiting for controller events…');
})();
</script>
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def find_unity_exe(version: str) -> Path | None:
    """Search Unity Hub install directories for a matching Editor version.

    Args:
        version: Full version string, e.g. "2018.3.8f1".

    Returns:
        Path to Unity.exe, or None if not found.
    """
    major_minor = ".".join(version.split(".")[:2])  # "2018.3"

    for root in UNITY_HUB_ROOTS:
        if not root.exists():
            continue

        # Exact match first
        exact = root / version / "Editor" / "Unity.exe"
        if exact.exists():
            return exact

        # Fuzzy: same major.minor (e.g. 2018.3.14f1 is close enough)
        for child in sorted(root.iterdir()):
            if child.name.startswith(major_minor):
                candidate = child / "Editor" / "Unity.exe"
                if candidate.exists():
                    return candidate

    return None


def get_unity_version(project: Path) -> str:
    """Read the Unity version from ProjectSettings/ProjectVersion.txt.

    Args:
        project: Root of the Unity project.

    Returns:
        Version string, e.g. "2018.3.8f1".
    """
    pv = project / "ProjectSettings" / "ProjectVersion.txt"
    for line in pv.read_text(encoding="utf-8").splitlines():
        if line.startswith("m_EditorVersion:"):
            return line.split(":", 1)[1].strip()
    raise RuntimeError(f"Cannot parse Unity version from {pv}")


def inject_build_script(project: Path) -> None:
    """Write WebGLBuilder.cs into Assets/Editor/ of the project.

    Args:
        project: Root of the Unity project.
    """
    editor_dir = project / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    (editor_dir / "WebGLBuilder.cs").write_text(WEBGL_BUILDER_CS, encoding="utf-8")
    print(f"  Injected WebGLBuilder.cs → {editor_dir}")


def run_unity_build(unity_exe: Path, project: Path) -> Path:
    """Invoke Unity in batchmode and return the path to the WebGL output.

    Args:
        unity_exe: Absolute path to Unity.exe.
        project: Root of the Unity project.

    Returns:
        Path to the WebGLBuild/ output directory.

    Raises:
        SystemExit: On non-zero Unity exit code or missing output.
    """
    log_file = project / "unity-build.log"
    cmd = [
        str(unity_exe),
        "-batchmode",
        "-quit",
        "-projectPath", str(project),
        "-buildTarget", "WebGL",
        "-executeMethod", "WebGLBuilder.Build",
        "-logFile", str(log_file),
    ]

    print(f"  Running: {' '.join(cmd[:4])} … (this takes 10-30 min, be patient)")
    result = subprocess.run(cmd, timeout=3600)

    # Always print last 50 log lines for visibility
    if log_file.exists():
        lines = log_file.read_text(encoding="utf-8", errors="replace").splitlines()
        print("\n--- Unity build log (last 50 lines) ---")
        for line in lines[-50:]:
            print(f"  {line}")
        print("--- end log ---\n")

    if result.returncode != 0:
        print(f"ERROR: Unity exited with code {result.returncode}. See {log_file}")
        sys.exit(1)

    output = project / "WebGLBuild"
    if not output.exists():
        print(f"ERROR: WebGLBuild/ not found in {project}. Build may have failed.")
        sys.exit(1)

    return output


def patch_index_html(dest: Path) -> None:
    """Inject the NEOARCADE gamepad bridge into Unity's generated index.html.

    Args:
        dest: Directory containing Unity's index.html.
    """
    index = dest / "index.html"
    if not index.exists():
        print(f"  WARNING: index.html not found in {dest}, skipping bridge patch.")
        return

    html = index.read_text(encoding="utf-8")

    if "NEOARCADE gamepad bridge" in html:
        print("  index.html already patched, skipping.")
        return

    # Inject right before </body>
    if "</body>" in html:
        html = html.replace("</body>", GAMEPAD_BRIDGE_JS + "</body>", 1)
    else:
        html += GAMEPAD_BRIDGE_JS

    index.write_text(html, encoding="utf-8")
    print(f"  Gamepad bridge injected into {index}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    """Entry point."""
    parser = argparse.ArgumentParser(
        description="Build MetalSlugClone (Unity 2018.3 WebGL) → public/games/slug/"
    )
    parser.add_argument(
        "--unity",
        metavar="PATH",
        help="Absolute path to Unity.exe (auto-detected from Unity Hub if omitted).",
    )
    parser.add_argument(
        "--project",
        metavar="PATH",
        help="Path to an existing MetalSlugClone clone (skips git clone).",
    )
    parser.add_argument(
        "--keep",
        action="store_true",
        help="Do NOT delete the temporary clone after build.",
    )
    args = parser.parse_args()

    tmp_dir: str | None = None

    # ── Step 1: get project path ───────────────────────────────────────────
    if args.project:
        project_path = Path(args.project).resolve()
        print(f"[1/5] Using existing project at {project_path}")
    else:
        tmp_dir = tempfile.mkdtemp(prefix="metalslug_")
        project_path = Path(tmp_dir)
        print(f"[1/5] Cloning {REPO_URL} …")
        subprocess.run(
            ["git", "clone", "--depth", "1", REPO_URL, str(project_path)],
            check=True,
        )
        print(f"      Cloned to {project_path}")

    try:
        # ── Step 2: locate Unity ───────────────────────────────────────────
        version = get_unity_version(project_path)
        print(f"[2/5] Project requires Unity {version}")

        if args.unity:
            unity_exe = Path(args.unity).resolve()
        else:
            unity_exe = find_unity_exe(version)  # type: ignore[assignment]

        if not unity_exe or not unity_exe.exists():
            print(
                f"\nERROR: Unity {version} not found.\n"
                "Options:\n"
                "  • Install it via Unity Hub (https://unity.com/download)\n"
                "  • Or pass --unity \"C:\\path\\to\\Unity.exe\"\n"
                "  • A close patch version (e.g. 2018.3.14f1) usually works fine."
            )
            sys.exit(1)

        print(f"      Found Unity at: {unity_exe}")

        # ── Step 3: inject C# build script ────────────────────────────────
        print("[3/5] Injecting WebGLBuilder.cs …")
        inject_build_script(project_path)

        # ── Step 4: run Unity WebGL build ──────────────────────────────────
        print("[4/5] Running Unity WebGL build …")
        build_output = run_unity_build(unity_exe, project_path)
        print(f"      Build output: {build_output}")

        # ── Step 5: copy to public/games/slug/ and patch index.html ────────
        print(f"[5/5] Copying to {OUTPUT_DIR} …")
        if OUTPUT_DIR.exists():
            shutil.rmtree(OUTPUT_DIR)
        shutil.copytree(build_output, OUTPUT_DIR)

        patch_index_html(OUTPUT_DIR)

        print("\n" + "=" * 60)
        print("SUCCESS — Metal Slug WebGL build is ready!")
        print(f"  Output: {OUTPUT_DIR}")
        print()
        print("Next steps:")
        print("  docker compose down && docker compose build && docker compose up -d")
        print("=" * 60)

    finally:
        if tmp_dir and not args.keep:
            shutil.rmtree(tmp_dir, ignore_errors=True)
            print(f"\n(Temp clone at {tmp_dir} deleted. Use --keep to preserve it.)")


if __name__ == "__main__":
    main()
